# Generated by Django 4.1 on 2022-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.CharField(help_text='Color Code Enter only', max_length=50),
        ),
    ]
