# Generated by Django 4.1 on 2022-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app1', '0002_alter_products_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.CharField(choices=[('good', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
