# Generated by Django 4.1 on 2022-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce_app1', '0003_alter_products_rating_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.CharField(choices=[(1, 'good'), (2, 'very good'), (3, 'bad'), (4, 'very bad')], max_length=50),
        ),
    ]
